logging:
  level:
    root: info

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/withjpa?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update